In [4]:
import pandas as pd
import os

DATA_PATH = 'C:\dev\github\SKN03-2nd-2Team\moonvie-crawling\data\season'
folder = os.listdir(DATA_PATH)
os.chdir(DATA_PATH)
for file in folder:
    df = pd.read_csv(file, encoding='utf-8-sig')
    df.head()

<>:4: SyntaxWarning: invalid escape sequence '\d'
<>:4: SyntaxWarning: invalid escape sequence '\d'
C:\Users\user\AppData\Local\Temp\ipykernel_2864\2591738344.py:4: SyntaxWarning: invalid escape sequence '\d'
  DATA_PATH = 'C:\dev\github\SKN03-2nd-2Team\moonvie-crawling\data\season'

In [10]:
import pandas as pd
import os

df = pd.read_csv('C:\dev\github\SKN03-2nd-2Team\moonvie-crawling\data\season\WeeklyBoxOfficeData.csv')

<>:4: SyntaxWarning: invalid escape sequence '\d'
<>:4: SyntaxWarning: invalid escape sequence '\d'
C:\Users\user\AppData\Local\Temp\ipykernel_23940\37528044.py:4: SyntaxWarning: invalid escape sequence '\d'
  df = pd.read_csv('C:\dev\github\SKN03-2nd-2Team\moonvie-crawling\data\season\WeeklyBoxOfficeData.csv')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4800 entries, 0 to 4799
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   박스오피스종류                4800 non-null   object
 1   상영기간                   4800 non-null   object
 2   조회연도및주차                4800 non-null   int64
 3   순번                     4800 non-null   int64
 4   박스오피스 순위               4800 non-null   int64
 5   전일대비 증감분               4800 non-null   int64
 6   신규진입여부                 4800 non-null   object
 7   영화대표코드                 4800 non-null   int64
 8   제목                     4800 non-null   object
 9   개봉일                    4800 non-null   object
 10  해당일자 매출액               4800 non-null   int64
 11  해당일자 상영작 대비 해당영화 매출비율  4800 non-null   float64
 12  전일대비 매출액 증감분           4800 non-null   int64
 13  전일대비 매출액 증감비율          4800 non-null   float64
 14  누적 매출액                 4800 non-null   int64
 15  해당일 관객수                4800 non-null   int64
 16  전일대비 관객수 증감분           4800 non-null   int64
 17  전일대비 관객수 증감비율          4800 non-null   float64
 18  누적 관객수                 4800 non-null   int64
 19  해당일자 상영 스크린수           4800 non-null   int64
 20  해당일자 상영 횟수             4800 non-null   int64
dtypes: float64(3), int64(13), object(5)
memory usage: 787.6+ KB

In [12]:
# 중복 행 제거
df = df.drop_duplicates()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3960 entries, 0 to 4779
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   박스오피스종류                3960 non-null   object
 1   상영기간                   3960 non-null   object
 2   조회연도및주차                3960 non-null   int64
 3   순번                     3960 non-null   int64
 4   박스오피스 순위               3960 non-null   int64
 5   전일대비 증감분               3960 non-null   int64
 6   신규진입여부                 3960 non-null   object
 7   영화대표코드                 3960 non-null   int64
 8   제목                     3960 non-null   object
 9   개봉일                    3960 non-null   object
 10  해당일자 매출액               3960 non-null   int64
 11  해당일자 상영작 대비 해당영화 매출비율  3960 non-null   float64
 12  전일대비 매출액 증감분           3960 non-null   int64
 13  전일대비 매출액 증감비율          3960 non-null   float64
 14  누적 매출액                 3960 non-null   int64
 15  해당일 관객수                3960 non-null   int64
 16  전일대비 관객수 증감분           3960 non-null   int64
 17  전일대비 관객수 증감비율          3960 non-null   float64
 18  누적 관객수                 3960 non-null   int64
 19  해당일자 상영 스크린수           3960 non-null   int64
 20  해당일자 상영 횟수             3960 non-null   int64
dtypes: float64(3), int64(13), object(5)
memory usage: 680.6+ KB

In [13]:
# 개봉일 column이 빈칸인 rows 찾아 제거
blank_value = ' '
column_name = '개봉일'
cnt = 0
if blank_value in df[column_name].values:
    matching_rows_idx = df[df[column_name] == blank_value].index
    for _ in matching_rows_idx:
        cnt += 1
    print(f'blank count: {cnt}\n {matching_rows_idx}')
    print('*'*30)

for matching_row in matching_rows_idx:
    df = df.drop(matching_row)

df.info()

blank count: 5
 Index([258, 1619, 2155, 2668, 3189], dtype='int64')
******************************
<class 'pandas.core.frame.DataFrame'>
Index: 3955 entries, 0 to 4779
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   박스오피스종류                3955 non-null   object
 1   상영기간                   3955 non-null   object
 2   조회연도및주차                3955 non-null   int64
 3   순번                     3955 non-null   int64
 4   박스오피스 순위               3955 non-null   int64
 5   전일대비 증감분               3955 non-null   int64
 6   신규진입여부                 3955 non-null   object
 7   영화대표코드                 3955 non-null   int64
 8   제목                     3955 non-null   object
 9   개봉일                    3955 non-null   object
 10  해당일자 매출액               3955 non-null   int64
 11  해당일자 상영작 대비 해당영화 매출비율  3955 non-null   float64
 12  전일대비 매출액 증감분           3955 non-null   int64
 13  전일대비 매출액 증감비율          3955 non-null   float64
 14  누적 매출액                 3955 non-null   int64
 15  해당일 관객수                3955 non-null   int64
 16  전일대비 관객수 증감분           3955 non-null   int64
 17  전일대비 관객수 증감비율          3955 non-null   float64
 18  누적 관객수                 3955 non-null   int64
 19  해당일자 상영 스크린수           3955 non-null   int64
 20  해당일자 상영 횟수             3955 non-null   int64
dtypes: float64(3), int64(13), object(5)
memory usage: 679.8+ KB

In [14]:
# 2017년 이전 개봉작 제거
df['개봉일'] = pd.to_datetime(df['개봉일'])
df = df[df['개봉일'] >= '2017-01-01']
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3833 entries, 0 to 4779
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   박스오피스종류                3833 non-null   object
 1   상영기간                   3833 non-null   object
 2   조회연도및주차                3833 non-null   int64
 3   순번                     3833 non-null   int64
 4   박스오피스 순위               3833 non-null   int64
 5   전일대비 증감분               3833 non-null   int64
 6   신규진입여부                 3833 non-null   object
 7   영화대표코드                 3833 non-null   int64
 8   제목                     3833 non-null   object
 9   개봉일                    3833 non-null   datetime64[ns]
 10  해당일자 매출액               3833 non-null   int64
 11  해당일자 상영작 대비 해당영화 매출비율  3833 non-null   float64
 12  전일대비 매출액 증감분           3833 non-null   int64
 13  전일대비 매출액 증감비율          3833 non-null   float64
 14  누적 매출액                 3833 non-null   int64
 15  해당일 관객수                3833 non-null   int64
 16  전일대비 관객수 증감분           3833 non-null   int64
 17  전일대비 관객수 증감비율          3833 non-null   float64
 18  누적 관객수                 3833 non-null   int64
 19  해당일자 상영 스크린수           3833 non-null   int64
 20  해당일자 상영 횟수             3833 non-null   int64
dtypes: datetime64[ns](1), float64(3), int64(13), object(4)
memory usage: 658.8+ KB

In [15]:
df.head()

,박스오피스종류,상영기간,조회연도및주차,순번,박스오피스 순위,전일대비 증감분,신규진입여부,영화대표코드,제목,개봉일,...,해당일자 상영작 대비 해당영화 매출비율,전일대비 매출액 증감분,전일대비 매출액 증감비율,누적 매출액,해당일 관객수,전일대비 관객수 증감분,전일대비 관객수 증감비율,누적 관객수,해당일자 상영 스크린수,해당일자 상영 횟수
0,주간 박스오피스,20240101~20240107,202401,1,1,0,OLD,20203702,노량: 죽음의 바다,2023-12-20,...,27.6,-10172692617,-58.8,41152784611,729900,-1026812,-58.5,4168033,1706,32060
1,주간 박스오피스,20240101~20240107,202401,2,2,0,OLD,20212866,서울의 봄,2023-11-22,...,26.4,-8412268008,-55.2,122176196329,684224,-862550,-55.8,12539003,1614,30527
2,주간 박스오피스,20240101~20240107,202401,3,3,37,OLD,20235834,위시,2024-01-03,...,23.2,5979016570,93876.8,5995723570,621537,620896,96863.7,622619,1421,25420
3,주간 박스오피스,20240101~20240107,202401,4,4,0,OLD,20236146,신차원! 짱구는 못말려 더 무비 초능력 대결전 ~날아라 수제김밥~,2023-12-22,...,6.7,-1644266149,-48.6,7242818414,180825,-170473,-48.5,749094,834,8470
4,주간 박스오피스,20240101~20240107,202401,5,5,-2,OLD,20235735,아쿠아맨과 로스트 킹덤,2023-12-20,...,4.7,-2392477113,-66.4,8669042503,122074,-230561,-65.4,845060,832,7689

In [16]:
# '영화대표코드'를 기준으로 그룹화한 후, '누적관객수'가 가장 높은 행의 인덱스를 선택
rows = df.groupby('영화대표코드')['누적 관객수'].idxmax()

# 선택된 인덱스의 행들만 남기기
df = df.loc[rows]

# 인덱스 재설정 (옵션)
df = df.reset_index(drop=True)
df

,박스오피스종류,상영기간,조회연도및주차,순번,박스오피스 순위,전일대비 증감분,신규진입여부,영화대표코드,제목,개봉일,...,해당일자 상영작 대비 해당영화 매출비율,전일대비 매출액 증감분,전일대비 매출액 증감비율,누적 매출액,해당일 관객수,전일대비 관객수 증감분,전일대비 관객수 증감비율,누적 관객수,해당일자 상영 스크린수,해당일자 상영 횟수
0,주간 박스오피스,20220704~20220710,202227,7,7,15,OLD,19978805,큐어,2022-07-06,...,0.2,73939000,404.3,122001600,8780,7360,518.3,11442,55,437
1,주간 박스오피스,20210118~20210124,202103,6,6,-1,OLD,20078386,블라인드,2021-01-14,...,0.9,-49731800,-53.1,138729200,4995,-5447,-52.2,15594,213,1689
2,주간 박스오피스,20180219~20180225,201808,8,8,-3,OLD,20078561,명탐정 코난:감벽의 관,2018-02-14,...,2.0,-694774100,-58.6,1688201900,68370,-88336,-56.4,226287,399,3478
3,주간 박스오피스,20200518~20200524,202021,9,9,-1,OLD,20113252,톰보이,2020-05-14,...,3.5,-34841920,-29.6,213762420,9458,-3391,-26.4,23992,308,2070
4,주간 박스오피스,20220627~20220703,202226,9,9,-1,OLD,20135304,극장판 포켓몬스터DP: 기라티나와 하늘의 꽃다발 쉐이미,2022-06-01,...,0.2,-39563980,-38.2,5442074270,6587,-4414,-40.1,577402,63,255
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1263,주간 박스오피스,20240429~20240505,202418,8,8,13,OLD,20249353,꼬마참새 리차드: 신비한 보석 탐험대,2024-05-01,...,0.3,119214700,883.6,146199300,16344,14890,1024.1,17798,174,877
1264,주간 박스오피스,20240527~20240602,202422,8,8,-2,OLD,20249416,청춘 18X2 너에게로 이어지는 길,2024-05-22,...,1.6,-449107539,-64.0,990307787,27431,-43563,-61.4,102090,549,4212
1265,주간 박스오피스,20240701~20240707,202427,8,8,0,OLD,20249507,극장판 하이큐!! 쓰레기장의 결전,2024-05-15,...,0.4,1824521,1.4,7323368219,13141,377,3.0,712092,107,608
1266,주간 박스오피스,20240805~20240811,202432,2,2,6,OLD,20249733,사랑의 하츄핑,2024-08-07,...,12.3,2793549502,738.3,3679174952,356704,318567,835.3,406387,1159,15225
1267,주간 박스오피스,20240527~20240602,202422,10,10,0,NEW,20249845,결속밴드 라이브 -항성-,2024-05-29,...,0.7,111595600,100.0,111595600,10112,10112,100.0,10112,72,624

In [17]:
from datetime import datetime

# '상영시작일'과 '상영종료일' 컬럼 생성
df[['상영시작일', '상영종료일']] = df['상영기간'].str.split('~', expand=True)

# '상영시작일'과 '상영종료일' 컬럼을 날짜 형식으로 변환
df['상영시작일'] = pd.to_datetime(df['상영시작일'], format='%Y%m%d')
df['상영종료일'] = pd.to_datetime(df['상영종료일'], format='%Y%m%d')

# 상영 기간을 월별로 분리하는 함수 정의
def get_months_range(start_date, end_date):
    months = set()
    current_date = start_date

    while current_date <= end_date:
        months.add(current_date.month)
        if current_date.month == 12:
            current_date = datetime(current_date.year + 1, 1, 1)
        else:
            current_date = datetime(current_date.year, current_date.month + 1, 1)

    return sorted(list(months))

# '상영연도'와 '상영월' 컬럼 생성
df['상영연도'] = df['상영시작일'].dt.year
df['상영월'] = df.apply(lambda row: ', '.join(map(str, get_months_range(row['상영시작일'], row['상영종료일']))), axis=1)

df = df[['영화대표코드', '제목', '개봉일', '해당일자 상영작 대비 해당영화 매출비율',
         '누적 매출액', '누적 관객수', '상영시작일', '상영종료일', '상영연도', '상영월']]

In [18]:
df.columns

Index(['영화대표코드', '제목', '개봉일', '해당일자 상영작 대비 해당영화 매출비율', '누적 매출액', '누적 관객수',
       '상영시작일', '상영종료일', '상영연도', '상영월'],
      dtype='object')

In [19]:
df

,영화대표코드,제목,개봉일,해당일자 상영작 대비 해당영화 매출비율,누적 매출액,누적 관객수,상영시작일,상영종료일,상영연도,상영월
0,19978805,큐어,2022-07-06,0.2,122001600,11442,2022-07-04,2022-07-10,2022,7
1,20078386,블라인드,2021-01-14,0.9,138729200,15594,2021-01-18,2021-01-24,2021,1
2,20078561,명탐정 코난:감벽의 관,2018-02-14,2.0,1688201900,226287,2018-02-19,2018-02-25,2018,2
3,20113252,톰보이,2020-05-14,3.5,213762420,23992,2020-05-18,2020-05-24,2020,5
4,20135304,극장판 포켓몬스터DP: 기라티나와 하늘의 꽃다발 쉐이미,2022-06-01,0.2,5442074270,577402,2022-06-27,2022-07-03,2022,"6, 7"
...,...,...,...,...,...,...,...,...,...,...
1263,20249353,꼬마참새 리차드: 신비한 보석 탐험대,2024-05-01,0.3,146199300,17798,2024-04-29,2024-05-05,2024,"4, 5"
1264,20249416,청춘 18X2 너에게로 이어지는 길,2024-05-22,1.6,990307787,102090,2024-05-27,2024-06-02,2024,"5, 6"
1265,20249507,극장판 하이큐!! 쓰레기장의 결전,2024-05-15,0.4,7323368219,712092,2024-07-01,2024-07-07,2024,7
1266,20249733,사랑의 하츄핑,2024-08-07,12.3,3679174952,406387,2024-08-05,2024-08-11,2024,8
1267,20249845,결속밴드 라이브 -항성-,2024-05-29,0.7,111595600,10112,2024-05-27,2024-06-02,2024,"5, 6"

In [20]:
df.to_csv('test.csv', encoding='utf-8-sig', index=False)

In [21]:
df.isnull().sum()

영화대표코드                   0
제목                       0
개봉일                      0
해당일자 상영작 대비 해당영화 매출비율    0
누적 매출액                   0
누적 관객수                   0
상영시작일                    0
상영종료일                    0
상영연도                     0
상영월                      0
dtype: int64

In [22]:
df = df.sort_values(by='누적 관객수', ascending=False)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1268 entries, 336 to 473
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   영화대표코드                 1268 non-null   int64
 1   제목                     1268 non-null   object
 2   개봉일                    1268 non-null   datetime64[ns]
 3   해당일자 상영작 대비 해당영화 매출비율  1268 non-null   float64
 4   누적 매출액                 1268 non-null   int64
 5   누적 관객수                 1268 non-null   int64
 6   상영시작일                  1268 non-null   datetime64[ns]
 7   상영종료일                  1268 non-null   datetime64[ns]
 8   상영연도                   1268 non-null   int32
 9   상영월                    1268 non-null   object
dtypes: datetime64[ns](3), float64(1), int32(1), int64(3), object(2)
memory usage: 104.0+ KB

# 분석

In [33]:
df = pd.read_csv('weekly_sample_data.csv', encoding='utf-8-sig', index_col=0)

In [34]:
df.head()

,제목,개봉일,해당일자 상영작 대비 해당영화 매출비율,누적 매출액,누적 관객수,상영시작일,상영종료일,상영연도,상영월
영화대표코드,,,,,,,,,
19978805,큐어,2022-07-06,0.2,122001600,11442,2022-07-04,2022-07-10,2022,7
20078386,블라인드,2021-01-14,0.9,138729200,15594,2021-01-18,2021-01-24,2021,1
20078561,명탐정 코난:감벽의 관,2018-02-14,2.0,1688201900,226287,2018-02-19,2018-02-25,2018,2
20113252,톰보이,2020-05-14,3.5,213762420,23992,2020-05-18,2020-05-24,2020,5
20135304,극장판 포켓몬스터DP: 기라티나와 하늘의 꽃다발 쉐이미,2022-06-01,0.2,5442074270,577402,2022-06-27,2022-07-03,2022,"6, 7"

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1268 entries, 19978805 to 20249845
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   제목                     1268 non-null   object
 1   개봉일                    1268 non-null   object
 2   해당일자 상영작 대비 해당영화 매출비율  1268 non-null   float64
 3   누적 매출액                 1268 non-null   int64
 4   누적 관객수                 1268 non-null   int64
 5   상영시작일                  1268 non-null   object
 6   상영종료일                  1268 non-null   object
 7   상영연도                   1268 non-null   int64
 8   상영월                    1268 non-null   object
dtypes: float64(1), int64(3), object(5)
memory usage: 99.1+ KB

In [36]:
df.describe()

       해당일자 상영작 대비 해당영화 매출비율        누적 매출액        누적 관객수         상영연도
count            1268.000000  1.268000e+03  1.268000e+03  1268.000000
mean                1.644322  7.352170e+09  8.243481e+05  2020.214511
std                 1.991408  1.658722e+10  1.833287e+06     2.203472
min                 0.000000  6.601000e+06  1.699000e+03  2017.000000
25%                 0.600000  3.181016e+08  3.567100e+04  2018.000000
50%                 1.100000  1.230122e+09  1.389800e+05  2020.000000
75%                 2.000000  6.164402e+09  6.823782e+05  2022.000000
max                46.600000  1.394945e+11  1.624323e+07  2024.000000

In [37]:
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib

# 한글 폰트 깨짐 방지
matplotlib.rcParams['font.family'] ='Malgun Gothic' 
matplotlib.rcParams['axes.unicode_minus'] =False

In [38]:
df.columns

Index(['제목', '개봉일', '해당일자 상영작 대비 해당영화 매출비율', '누적 매출액', '누적 관객수', '상영시작일',
       '상영종료일', '상영연도', '상영월'],
      dtype='object')

In [ ]:
df_category